env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
ignorePatterns:
  - "packages/**/dist/*"
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
rules:
  max-len: [2, 120, 4]
