# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Build and Publishing to NPM Site

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'lambdatest'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: PUBLISHING test-at-scale-js from release ${{ github.event.release.tag_name }}
        run: |
          npm ci
          npm run publish --access public
          echo "CHECKING on NPM REPO, whether new version starts reflecting there or not:";
          npm view @lambdatest/test-at-scale-core versions --json
          npm view @lambdatest/test-at-scale-jasmine-runner versions --json
          npm view @lambdatest/test-at-scale-jest-runner versions --json
          npm view @lambdatest/test-at-scale-mocha-runner versions --json
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.17.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "`test-at-scale-js` GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
