name: Lint
on:
  pull_request:
    branches:
      - main
jobs:
  Lint:
    name: CI - Lint
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: Run es-lint
        run: yarn install && yarn lint
